############# Incoming Messages ##########################
mp.messaging.incoming.input-queue.connector=smallrye-rabbitmq
mp.messaging.incoming.input-queue.queue.name=input-message-queue
mp.messaging.incoming.input-queue.exchange.name=input-message-exchange
mp.messaging.incoming.input-queue.queue.declare=true

############# Output Exchange Configuration ####################
mp.messaging.outgoing.output-exchange.connector=smallrye-rabbitmq
mp.messaging.outgoing.output-exchange.exchange.name=output-message-exchange
mp.messaging.outgoing.output-exchange.exchange.type=topic
mp.messaging.outgoing.output-exchange.exchange.declare=true
mp.messaging.outgoing.output-exchange.default-routing-key=default-key

############# Incoming Messages ##########################
mp.messaging.outgoing.input-queue-test.connector=smallrye-rabbitmq
mp.messaging.outgoing.input-queue-test.exchange.name=input-message-exchange
mp.messaging.outgoing.input-queue-test.exchange.type=topic
mp.messaging.outgoing.input-queue-test.exchange.declare=true
mp.messaging.outgoing.input-queue-test.default-routing-key=default-key

############# Output Queue Configuration (just for tests) ####################
mp.messaging.incoming.output-exchange-test.connector=smallrye-rabbitmq
mp.messaging.incoming.output-exchange-test.exchange.name=${mp.messaging.outgoing.output-exchange.exchange.name}
mp.messaging.incoming.output-exchange-test.exchange.type=${mp.messaging.outgoing.output-exchange.exchange.type}
mp.messaging.incoming.output-exchange-test.queue.name=output-message-queue
mp.messaging.incoming.output-exchange-test.routing-keys=${mp.messaging.outgoing.output-exchange.default-routing-key}
mp.messaging.incoming.output-exchange-test.auto-acknowledgement=true
# We need to declare the test queue.
mp.messaging.incoming.output-exchange-test.queue.declare=true

# This exception occurs when testcontainer stops. It is not informative and doesn't break anything, just spoils the log.
quarkus.log.category."com.rabbitmq.client.impl.ForgivingExceptionHandler".level=OFF
